### ISSUE TITLE
Swerve Drive Calibration Process

### ISSUE THREAD

**Issue by nfurno** [FRCTeam8544/crescendo#7]
Please document the swerve drive calibration process, or point at the vendor documentation using a link.
Include any notes about the process that you learned which would benefit us if we have to calibrate the swerve drive again in the future.

**Comment by untitledfish** [comment]
ctrl c ctrl v our current swerve code for the most part, and the navX vendordep can be found at https://dev.studica.com/releases/202-/NavX.json (replace - with current year)
